using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    public const string StyleIdentifierMainMenu = "mainMenu";
    public const string StyleIdentifierMainMenuVBox = "mainMenuVBox";

    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.TopRight);
        LayoutContainer.SetMarginRight(VBox, 64);
        LayoutContainer.SetMarginTop(VBox, 64);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Begin);

        Background.Texture = resCache.GetResource<TextureResource>("/Textures/Ashfall/UI/main-menu-splash.png");

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;
    }
}
