// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Trauma.Knowledge;
using Content.Shared.Humanoid.Prototypes;
using Content.Trauma.Common.Knowledge;
using Content.Trauma.Common.Knowledge.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Trauma.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeProfileEditor : BoxContainer
{
    private readonly IPrototypeManager _proto;
    private readonly KnowledgeSystem _knowledge;

    public event Action<KnowledgeProfile>? OnSave;

    private KnowledgeProfilePrototype _parent = default!;
    private KnowledgeProfile _profile = new();
    private bool _modified;

    public KnowledgeProfileEditor(IPrototypeManager proto, KnowledgeSystem knowledge)
    {
        RobustXamlLoader.Load(this);

        _proto = proto;
        _knowledge = knowledge;

        SaveButton.OnPressed += _ =>
        {
            OnSave?.Invoke(_profile);
            _modified = false;
            SaveButton.Disabled = true;
        };

        ResetButton.OnPressed += _ =>
        {
            _profile = new();
            _modified = true;
            ResetButton.Disabled = true;
            ReloadSkills();
        };
    }

    public void SetProfile(ProtoId<SpeciesPrototype> species, KnowledgeProfile profile)
    {
        _profile = profile;
        var speciesProto = _proto.Index(species);
        _parent = _proto.Index(speciesProto.Knowledge);
        ReloadSkills();
        UpdateReset();
    }

    private void ReloadSkills()
    {
        Dictionary<ProtoId<KnowledgeCategoryPrototype>, BoxContainer> categories = [];
        UpdatePoints();

        EnabledSkills.RemoveAllChildren();
        foreach (var (id, comp) in _knowledge.AllKnowledges)
        {
            var proto = _proto.Index(id);
            var name = proto.Name;
            var desc = proto.Description;
            if (comp.Costs is not { } costs)
                continue;

            var control = new SkillControl(name, costs);
            control.ToolTip = desc;
            var racialBase = _parent.Profile.Mastery.GetValueOrDefault(id);
            var mastery = _profile.Mastery.GetValueOrDefault(id) + racialBase;

            control.SetMastery(_knowledge.GetMasteryString(mastery), mastery, racialBase);

            control.OnChangeMastery += diff =>
            {
                var sum = control.Mastery + diff;
                if (sum >= costs.Length || sum < racialBase)
                    return;

                control.SetMastery(_knowledge.GetMasteryString(sum), sum, racialBase);
                if (sum == 0)
                    _profile.Mastery.Remove(id);
                else
                    _profile.Mastery[id] = _profile.Mastery.GetValueOrDefault(id) + diff;

                _modified = true;
                UpdatePoints();
                UpdateReset();
            };

            if (categories.TryGetValue(comp.Category, out var category))
            {
                category.AddChild(control);
            }
            else
            {
                var newCategory = new SkillCategory(Loc.GetString(_proto.Index(comp.Category).Name));
                EnabledSkills.AddChild(newCategory);
                newCategory.AddChild(control);
                categories.TryAdd(comp.Category, newCategory);
            }
        }
    }

    private void UpdatePoints()
    {
        var points = _parent.PointsLimit;
        var cost = _knowledge.ProfileCost(_profile);
        points -= cost;
        PointsLabel.Text = Loc.GetString("knowledge-editor-points", ("points", points));
        if (points >= 0)
        {
            PointsLabel.FontColorOverride = Color.White;
            SaveButton.Disabled = !_modified;
            return;
        }

        PointsLabel.FontColorOverride = Color.Red;
        SaveButton.Disabled = true;
    }

    private void UpdateReset()
    {
        ResetButton.Disabled = true;
        foreach (var level in _profile.Mastery.Values)
        {
            if (level != 0)
            {
                ResetButton.Disabled = false;
                break;
            }
        }
    }
}
