// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Trauma.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillCategory : BoxContainer
{
    public SkillCategory(string name)
    {
        RobustXamlLoader.Load(this);

        SkillLabel.Text = name;
    }
}
