// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Trauma.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillControl : BoxContainer
{
    public event Action<int>? OnChangeMastery;
    private readonly int[] _costs;
    public int Mastery;

    public SkillControl(string name, int[] costs)
    {
        RobustXamlLoader.Load(this);

        _costs = costs;

        SkillLabel.Text = name;

        DecreaseButton.OnPressed += _ => OnChangeMastery?.Invoke(-1);
        IncreaseButton.OnPressed += _ => OnChangeMastery?.Invoke(+1);
    }

    public void SetMastery(string name, int mastery, int racialBase = 0)
    {
        Mastery = mastery;
        var cost = _costs[Math.Max(mastery - racialBase, 0)];
        MasteryLabel.Text = Loc.GetString("knowledge-editor-mastery", ("mastery", name), ("cost", cost));
        IncreaseButton.Disabled = mastery >= _costs.Length - 1;
        DecreaseButton.Disabled = mastery <= racialBase;
        var color = mastery <= 0 ? Color.Gray : Color.White;
        MasteryLabel.Modulate = color;
        SkillLabel.Modulate = color;
    }
}
