using System.Linq;
using Ashfall.Client.Stylesheets;
using Content.Client.Trauma.Knowledge;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Trauma.Common.Knowledge;
using Content.Trauma.Common.Knowledge.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Ashfall.CharacterGen.UI;

[GenerateTypedNameReferences]
public sealed partial class AshfallSkillsDetailWindow : DefaultWindow
{
    private readonly IPrototypeManager _proto;
    private readonly KnowledgeSystem _knowledge;

    public AshfallSkillsDetailWindow(IPrototypeManager proto, KnowledgeSystem knowledge)
    {
        RobustXamlLoader.Load(this);
        _proto = proto;
        _knowledge = knowledge;

        DetailsCloseButton.OnPressed += _ => Close();
    }

    public void Populate(HumanoidCharacterProfile profile, JobPrototype? job)
    {
        Title = Loc.GetString("ashfall-skills-window-title", ("name", profile.Name));
        CandidateNameLabel.Text = profile.Name;

        var sex = profile.Sex switch
        {
            Sex.Male => Loc.GetString("ashfall-personal-files-sex-male"),
            Sex.Female => Loc.GetString("ashfall-personal-files-sex-female"),
            _ => Loc.GetString("ashfall-personal-files-sex-other"),
        };
        var speciesName = _proto.TryIndex<SpeciesPrototype>(profile.Species, out var speciesProto)
            ? Loc.GetString(speciesProto.Name)
            : profile.Species.Id;

        CandidateBioLabel.Text = Loc.GetString("ashfall-personal-files-dossier-bio", ("age", profile.Age), ("sex", sex), ("species", speciesName));

        var jobName = job?.LocalizedName ?? Loc.GetString("ashfall-personal-files-record-unavailable");
        CandidateJobLabel.Text = Loc.GetString("ashfall-skills-window-job", ("job", jobName));

        CategoriesContainer.RemoveAllChildren();

        // Retrieve species baseline profile
        KnowledgeProfilePrototype? speciesKnowledge = null;
        if (speciesProto != null && _proto.TryIndex(speciesProto.Knowledge, out KnowledgeProfilePrototype? spk))
            speciesKnowledge = spk;

        var categories = _proto.EnumeratePrototypes<KnowledgeCategoryPrototype>()
            .OrderBy(c => c.ID)
            .ToList();

        foreach (var category in categories)
        {
            var skillsInCategory = _knowledge.AllKnowledges
                .Where(kvp => kvp.Value.Category == category.ID)
                .OrderBy(kvp => kvp.Key.Id)
                .ToList();

            if (skillsInCategory.Count == 0)
                continue;

            var categoryBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                HorizontalExpand = true,
            };

            var catTitle = Loc.TryGetString(category.Name, out var locCat) ? locCat : category.ID;
            var catHeader = new RichTextLabel
            {
                HorizontalExpand = true,
                Text = $"[color={AshfallStylesheet.PrimaryAmber.ToHex()}][bold]{FormattedMessage.EscapeText(catTitle.ToUpperInvariant())}[/bold][/color]",
            };
            categoryBox.AddChild(catHeader);

            foreach (var (skillId, comp) in skillsInCategory)
            {
                var speciesBase = speciesKnowledge?.Profile.Mastery.GetValueOrDefault(skillId) ?? 0;
                var profileDiff = profile.Knowledge.Mastery.GetValueOrDefault(skillId);
                var candidateBase = speciesBase + profileDiff;
                var jobFloor = job?.Knowledge.GetValueOrDefault(skillId) ?? 0;
                var effectiveMastery = Math.Max(jobFloor, candidateBase);

                var skillName = GetSkillName(skillId, _proto);
                var skillDesc = GetSkillDescription(skillId, _proto);
                var masteryStr = _knowledge.GetMasteryString(effectiveMastery);
                var roman = ToRoman(effectiveMastery);

                var skillCard = new PanelContainer
                {
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 2, 0, 2),
                };
                skillCard.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex(effectiveMastery > 0 ? "#1E2022" : "#171819"),
                    BorderColor = Color.FromHex(effectiveMastery > 0 ? "#43464B" : "#2E3033"),
                    BorderThickness = new Thickness(1),
                };

                var cardContent = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(8, 6),
                    SeparationOverride = 2,
                    HorizontalExpand = true,
                };

                var titleColor = effectiveMastery > 0 ? AshfallStylesheet.PrimaryAmber : Color.FromHex("#878C87");
                var levelColor = effectiveMastery > 0 ? "#5E8B82" : "#878C87";

                var headerRich = new RichTextLabel
                {
                    HorizontalExpand = true,
                    Text = $"[color={titleColor.ToHex()}][bold]{FormattedMessage.EscapeText(skillName)}[/bold][/color] — [color={levelColor}]{masteryStr} ({roman})[/color]",
                };
                cardContent.AddChild(headerRich);

                if (!string.IsNullOrEmpty(skillDesc))
                {
                    var descLabel = new RichTextLabel { HorizontalExpand = true };
                    descLabel.SetMessage(skillDesc, Color.FromHex("#A3A8A3"));
                    cardContent.AddChild(descLabel);
                }

                var breakdownText = Loc.GetString("ashfall-skills-window-breakdown",
                    ("species", speciesBase),
                    ("profile", profileDiff),
                    ("job", jobFloor));
                var breakdownLabel = new Label
                {
                    Text = breakdownText,
                    FontColorOverride = Color.FromHex("#686B68"),
                };
                cardContent.AddChild(breakdownLabel);

                skillCard.AddChild(cardContent);
                categoryBox.AddChild(skillCard);
            }

            CategoriesContainer.AddChild(categoryBox);
        }
    }

    public static string GetSkillName(EntProtoId skillId, IPrototypeManager proto)
    {
        if (Loc.TryGetString($"ent-{skillId}", out var name))
            return name;

        var key = skillId.Id switch
        {
            "SurgeryKnowledge" => "knowledge-skill-surgery",
            "FirstAidKnowledge" => "knowledge-skill-first-aid",
            "ShootingKnowledge" => "knowledge-skill-marksmanship",
            "MeleeKnowledge" => "knowledge-skill-unarmed",
            "KnowledgeWeaponsBludgeon" => "knowledge-skill-bludgeon",
            "KnowledgeWeaponsShortBlade" => "knowledge-skill-short-blade",
            "KnowledgeWeaponsLongBlade" => "knowledge-skill-long-blade",
            "KnowledgeWeaponsPolearm" => "knowledge-skill-polearm",
            "KnowledgeWeaponsNonLethal" => "knowledge-skill-nonlethal",
            "KnowledgeWeaponsTool" => "knowledge-skill-tool-combat",
            "KnowledgeWeaponsShield" => "knowledge-skill-shield",
            "KnowledgeWeaponsEnergy" => "knowledge-skill-energy",
            "KnowledgeWeaponsPistol" => "knowledge-skill-pistol",
            "KnowledgeWeaponsRifle" => "knowledge-skill-rifle",
            "KnowledgeWeaponsSMG" => "knowledge-skill-smg",
            "KnowledgeWeaponsShotgun" => "knowledge-skill-shotgun",
            "KnowledgeWeaponsLaser" => "knowledge-skill-laser",
            "ThrowingKnowledge" => "knowledge-skill-throwing",
            "AthleticsKnowledge" => "knowledge-skill-stamina",
            "StaminaKnowledge" => "knowledge-skill-stamina",
            "StrengthKnowledge" => "knowledge-skill-strength",
            "FabricationKnowledge" => "knowledge-skill-fabrication",
            _ => null,
        };

        if (key != null && Loc.TryGetString(key, out var mappedName))
            return mappedName;

        if (proto.TryIndex(skillId, out var entityProto) && !string.IsNullOrEmpty(entityProto.Name))
            return entityProto.Name;

        return skillId.Id;
    }

    public static string GetSkillDescription(EntProtoId skillId, IPrototypeManager proto)
    {
        if (Loc.TryGetString($"ent-{skillId}.desc", out var desc))
            return desc;

        var key = skillId.Id switch
        {
            "SurgeryKnowledge" => "knowledge-skill-surgery-desc",
            "FirstAidKnowledge" => "knowledge-skill-first-aid-desc",
            "ShootingKnowledge" => "knowledge-skill-marksmanship-desc",
            "MeleeKnowledge" => "knowledge-skill-unarmed-desc",
            "KnowledgeWeaponsBludgeon" => "knowledge-skill-bludgeon-desc",
            "KnowledgeWeaponsShortBlade" => "knowledge-skill-short-blade-desc",
            "KnowledgeWeaponsLongBlade" => "knowledge-skill-long-blade-desc",
            "KnowledgeWeaponsPolearm" => "knowledge-skill-polearm-desc",
            "KnowledgeWeaponsNonLethal" => "knowledge-skill-nonlethal-desc",
            "KnowledgeWeaponsTool" => "knowledge-skill-tool-combat-desc",
            "KnowledgeWeaponsShield" => "knowledge-skill-shield-desc",
            "KnowledgeWeaponsEnergy" => "knowledge-skill-energy-desc",
            "KnowledgeWeaponsPistol" => "knowledge-skill-pistol-desc",
            "KnowledgeWeaponsRifle" => "knowledge-skill-rifle-desc",
            "KnowledgeWeaponsSMG" => "knowledge-skill-smg-desc",
            "KnowledgeWeaponsShotgun" => "knowledge-skill-shotgun-desc",
            "KnowledgeWeaponsLaser" => "knowledge-skill-laser-desc",
            "ThrowingKnowledge" => "knowledge-skill-throwing-desc",
            "AthleticsKnowledge" => "knowledge-skill-stamina-desc",
            "StaminaKnowledge" => "knowledge-skill-stamina-desc",
            "StrengthKnowledge" => "knowledge-skill-strength-desc",
            "FabricationKnowledge" => "knowledge-skill-fabrication-desc",
            _ => null,
        };

        if (key != null && Loc.TryGetString(key, out var mappedDesc))
            return mappedDesc;

        if (proto.TryIndex(skillId, out var entityProto) && !string.IsNullOrEmpty(entityProto.Description))
            return entityProto.Description;

        return string.Empty;
    }

    public static string ToRoman(int number) => number switch
    {
        1 => "I",
        2 => "II",
        3 => "III",
        4 => "IV",
        5 => "V",
        _ => "0",
    };
}
