using Ashfall.Client.Stylesheets;
using Content.Client.Message;
using Content.Shared.Ashfall.CharacterGen;
using Content.Shared.Ashfall.CharacterGen.Prototypes;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Ashfall.CharacterGen.UI;

[GenerateTypedNameReferences]
public sealed partial class AshfallCultureDetailWindow : DefaultWindow
{
    private readonly IPrototypeManager _proto;

    public AshfallCultureDetailWindow(IPrototypeManager proto)
    {
        RobustXamlLoader.Load(this);
        _proto = proto;

        DetailsCloseButton.OnPressed += _ => Close();
    }

    public void Populate(HumanoidCharacterProfile profile, AshfallCharacterDossier dossier)
    {
        Title = Loc.GetString("ashfall-culture-window-title", ("name", profile.Name));
        CandidateNameLabel.Text = profile.Name;

        var sex = profile.Sex switch
        {
            Sex.Male => Loc.GetString("ashfall-personal-files-sex-male"),
            Sex.Female => Loc.GetString("ashfall-personal-files-sex-female"),
            _ => Loc.GetString("ashfall-personal-files-sex-other"),
        };
        var speciesName = _proto.TryIndex<SpeciesPrototype>(profile.Species, out var speciesProto)
            ? Loc.GetString(speciesProto.Name)
            : profile.Species.Id;

        CandidateBioLabel.Text = Loc.GetString("ashfall-personal-files-dossier-bio", ("age", profile.Age), ("sex", sex), ("species", speciesName));

        var cultureGap = new string('\u00A0', 2);
        var cultureLine = !string.IsNullOrEmpty(dossier.Morphology)
            ? $"МОРФОЛОГИЯ // {dossier.Morphology}{cultureGap}•{cultureGap}КУЛЬТУРНАЯ ЛИНИЯ // {dossier.CulturalOrigin}"
            : (!string.IsNullOrEmpty(dossier.CulturalOrigin)
                ? $"КУЛЬТУРНАЯ ЛИНИЯ // {dossier.CulturalOrigin}"
                : string.Empty);
        CandidateCultureLabel.SetMarkup(string.IsNullOrEmpty(cultureLine)
            ? string.Empty
            : $"[color=#878C87]{cultureLine}[/color]");

        ContentContainer.RemoveAllChildren();

        // 1. Species Overview Card
        var speciesIdLower = profile.Species.Id.ToLowerInvariant();
        AddLoreCard(
            Loc.GetString("ashfall-culture-window-species-header", ("species", speciesName)),
            $"ashfall-species-lore-{speciesIdLower}-desc",
            $"ashfall-species-lore-{speciesIdLower}-traits",
            Loc.GetString("ashfall-culture-window-species-traits-header"));

        // 2. Cultural Group Overview Card
        if (dossier.CultureId != null && _proto.TryIndex(dossier.CultureId.Value, out AshfallCulturePrototype? cultureProto))
        {
            var cultureIdLower = cultureProto.ID.ToLowerInvariant();
            var cultureName = Loc.GetString(cultureProto.Label);
            AddLoreCard(
                Loc.GetString("ashfall-culture-window-culture-header", ("culture", cultureName)),
                $"ashfall-culture-lore-{cultureIdLower}-desc",
                $"ashfall-culture-lore-{cultureIdLower}-rituals",
                Loc.GetString("ashfall-culture-window-culture-rituals-header"));
        }
    }

    private void AddLoreCard(string headerTitle, string descLocKey, string detailsLocKey, string detailsHeading)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
        };
        card.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#161718"),
            BorderColor = Color.FromHex("#2E3134"),
            BorderThickness = new Thickness(1),
        };

        var cardContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 10),
            SeparationOverride = 8,
            HorizontalExpand = true,
        };

        // Title
        var headerLabel = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        headerLabel.SetMarkup($"[color={AshfallStylesheet.PrimaryAmber.ToHex()}][bold]{FormattedMessage.EscapeText(headerTitle.ToUpperInvariant())}[/bold][/color]");
        cardContent.AddChild(headerLabel);

        // Main description
        if (Loc.TryGetString(descLocKey, out var descText))
        {
            var descRich = new RichTextLabel { HorizontalExpand = true };
            descRich.SetMessage(descText, Color.FromHex("#D0D5D0"));
            cardContent.AddChild(descRich);
        }

        // Specific rituals/traits
        if (Loc.TryGetString(detailsLocKey, out var detailsText))
        {
            var subHeader = new Label
            {
                Text = detailsHeading,
                FontColorOverride = Color.FromHex("#5E8B82"),
            };
            cardContent.AddChild(subHeader);

            var detailsRich = new RichTextLabel { HorizontalExpand = true };
            detailsRich.SetMessage(detailsText, Color.FromHex("#A3A8A3"));
            cardContent.AddChild(detailsRich);
        }

        card.AddChild(cardContent);
        ContentContainer.AddChild(card);
    }
}
