name: Build & Test

on:
  push:
    branches: [ wizards ]
  pull_request:
    branches: [ wizards ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test .NET 8
      run: dotnet test --configuration Release --framework net8.0 -v n
    - name: Test .NET 9
      run: dotnet test --configuration Release --framework net9.0 -v n
    - name: Test .NET 10
      run: dotnet test --configuration Release --framework net10.0 -v n
