using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    public static event Action<CharacterWindow>? OnOpened;

    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Opened()
    {
        base.Opened();
        OnOpened?.Invoke(this);
    }
}
