//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_preference_observer_t
    {
        internal cef_base_ref_counted_t _base;
        internal delegate* unmanaged<cef_preference_observer_t*, cef_string_t*, void> _on_preference_changed;
        
        internal GCHandle _obj;
        
        [UnmanagedCallersOnly]
        public static void add_ref(cef_preference_observer_t* self)
        {
            var obj = (CefPreferenceObserver)self->_obj.Target;
            obj.add_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static int release(cef_preference_observer_t* self)
        {
            var obj = (CefPreferenceObserver)self->_obj.Target;
            return obj.release(self);
        }
        
        [UnmanagedCallersOnly]
        public static int has_one_ref(cef_preference_observer_t* self)
        {
            var obj = (CefPreferenceObserver)self->_obj.Target;
            return obj.has_one_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static int has_at_least_one_ref(cef_preference_observer_t* self)
        {
            var obj = (CefPreferenceObserver)self->_obj.Target;
            return obj.has_at_least_one_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static void on_preference_changed(cef_preference_observer_t* self, cef_string_t* name)
        {
            var obj = (CefPreferenceObserver)self->_obj.Target;
            obj.on_preference_changed(self, name);
        }
        
        internal static cef_preference_observer_t* Alloc()
        {
            var ptr = (cef_preference_observer_t*)NativeMemory.Alloc((UIntPtr)sizeof(cef_preference_observer_t));
            *ptr = default(cef_preference_observer_t);
            ptr->_base._size = (UIntPtr)sizeof(cef_preference_observer_t) - 8;
            ptr->_base._add_ref = (delegate* unmanaged<cef_base_ref_counted_t*, void>)(delegate* unmanaged<cef_preference_observer_t*, void>)&add_ref;
            ptr->_base._release = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_preference_observer_t*, int>)&release;
            ptr->_base._has_one_ref = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_preference_observer_t*, int>)&has_one_ref;
            ptr->_base._has_at_least_one_ref = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_preference_observer_t*, int>)&has_at_least_one_ref;
            ptr->_on_preference_changed = &on_preference_changed;
            return ptr;
        }
        
        internal static void Free(cef_preference_observer_t* ptr)
        {
            NativeMemory.Free((void*)ptr);
        }
        
    }
}
