//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_thread_t
    {
        internal cef_base_ref_counted_t _base;
        internal delegate* unmanaged<cef_thread_t*, cef_task_runner_t*> _get_task_runner;
        internal delegate* unmanaged<cef_thread_t*, cef_platform_thread_id_t> _get_platform_thread_id;
        internal delegate* unmanaged<cef_thread_t*, void> _stop;
        internal delegate* unmanaged<cef_thread_t*, int> _is_running;
        
        // CreateThread
        [DllImport(libcef.DllName, EntryPoint = "cef_thread_create", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_thread_t* create(cef_string_t* display_name, cef_thread_priority_t priority, cef_message_loop_type_t message_loop_type, int stoppable, cef_com_init_mode_t com_init_mode);
        
        // AddRef
        
        public static void add_ref(cef_thread_t* self)
        {
            self->_base._add_ref((cef_base_ref_counted_t*)self);
        }
        
        // Release
        
        public static int release(cef_thread_t* self)
        {
            return self->_base._release((cef_base_ref_counted_t*)self);
        }
        
        // HasOneRef
        
        public static int has_one_ref(cef_thread_t* self)
        {
            return self->_base._has_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // HasAtLeastOneRef
        
        public static int has_at_least_one_ref(cef_thread_t* self)
        {
            return self->_base._has_at_least_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // GetTaskRunner
        
        public static cef_task_runner_t* get_task_runner(cef_thread_t* self)
        {
            return self->_get_task_runner(self);
        }
        
        // GetPlatformThreadId
        
        public static cef_platform_thread_id_t get_platform_thread_id(cef_thread_t* self)
        {
            return self->_get_platform_thread_id(self);
        }
        
        // Stop
        
        public static void stop(cef_thread_t* self)
        {
            self->_stop(self);
        }
        
        // IsRunning
        
        public static int is_running(cef_thread_t* self)
        {
            return self->_is_running(self);
        }
        
    }
}
