//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_waitable_event_t
    {
        internal cef_base_ref_counted_t _base;
        internal delegate* unmanaged<cef_waitable_event_t*, void> _reset;
        internal delegate* unmanaged<cef_waitable_event_t*, void> _signal;
        internal delegate* unmanaged<cef_waitable_event_t*, int> _is_signaled;
        internal delegate* unmanaged<cef_waitable_event_t*, void> _wait;
        internal delegate* unmanaged<cef_waitable_event_t*, long, int> _timed_wait;
        
        // CreateWaitableEvent
        [DllImport(libcef.DllName, EntryPoint = "cef_waitable_event_create", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_waitable_event_t* create(int automatic_reset, int initially_signaled);
        
        // AddRef
        
        public static void add_ref(cef_waitable_event_t* self)
        {
            self->_base._add_ref((cef_base_ref_counted_t*)self);
        }
        
        // Release
        
        public static int release(cef_waitable_event_t* self)
        {
            return self->_base._release((cef_base_ref_counted_t*)self);
        }
        
        // HasOneRef
        
        public static int has_one_ref(cef_waitable_event_t* self)
        {
            return self->_base._has_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // HasAtLeastOneRef
        
        public static int has_at_least_one_ref(cef_waitable_event_t* self)
        {
            return self->_base._has_at_least_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // Reset
        
        public static void reset(cef_waitable_event_t* self)
        {
            self->_reset(self);
        }
        
        // Signal
        
        public static void signal(cef_waitable_event_t* self)
        {
            self->_signal(self);
        }
        
        // IsSignaled
        
        public static int is_signaled(cef_waitable_event_t* self)
        {
            return self->_is_signaled(self);
        }
        
        // Wait
        
        public static void wait(cef_waitable_event_t* self)
        {
            self->_wait(self);
        }
        
        // TimedWait
        
        public static int timed_wait(cef_waitable_event_t* self, long max_ms)
        {
            return self->_timed_wait(self, max_ms);
        }
        
    }
}
