//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const int CEF_API_VERSION = 14100;
        public const string CEF_VERSION = "141.0.11+g7e73ac4+chromium-141.0.7390.123";
        public const int CEF_VERSION_MAJOR = 141;
        public const int CEF_COMMIT_NUMBER = 3299;
        public const string CEF_COMMIT_HASH = "7e73ac45f2979537f677e785383a04998f90d51d";
        
        public const int CHROME_VERSION_MAJOR = 141;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 7390;
        public const int CHROME_VERSION_PATCH = 123;
        
        public const string CEF_API_HASH_PLATFORM_WIN = "2948bec685a469a829d99eb1e6b08ede0ff9b197";
        public const string CEF_API_HASH_PLATFORM_MACOS = "9537beb8d28175dca77510c03f5bea55617a9f22";
        public const string CEF_API_HASH_PLATFORM_LINUX = "f0f231efab94eb818114490804b13fce61ab7f4e";
    }
}
